food: sushi
iptables_allowed_tcp_ports: [22,80]
nginx_sites:
  default:
    - listen 80
    - server_name "localhost"
    - root "/srv/web"
    - location ~* /(?:uploads|files)/.*\.php$ {
        deny all;
      }
    - location / {
        index index.php index.html index.htm;
        try_files $uri $uri/ /index.php?$args;
      }
    - location ~* \.(gif|jpg|jpeg|png|css|js)$ {
        expires max;
      }
    - location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_index index.php;
        fastcgi_pass  unix:/var/run/wordpress.sock;
        fastcgi_param   SCRIPT_FILENAME
                        $document_root$fastcgi_script_name;
        include       fastcgi_params;
      }

